version: "3.8"
services:
    sqldata:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          - SA_PASSWORD=Pass@word
          - ACCEPT_EULA=Y
        ports:
          - 5434:1433
    googlesrival:
        build: 
            context: .
            dockerfile: GooglesRival/Dockerfile
        environment: 
            ASPNETCORE_ENVIRONMENT: Development
            ConnectionString: SERVER=sqldata;DATABASE=MyAPI;User ID=sa;Password=Pass@word;
        image: calromamccluskey/trainingmyapi
        restart: on-failure
        ports:
              - 8123:80
        depends_on:
            - sqldata
        container_name: googles_rival_ContainerName
networks:
    default:
        name: google_default