USE [MyAPI]
GO

/****** Object:  Table [dbo].[MyAPI_Users]    Script Date: 19/02/2021 17:45:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MyAPI_Users](
	[MyAPI_Users_ID] [int] IDENTITY(1,1) NOT NULL,
	[MyAPI_Users_Username] [varchar](50) NOT NULL,
	[MyAPI_Users_Password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_MyAPI_Users] PRIMARY KEY CLUSTERED 
(
	[MyAPI_Users_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


